# Generated by Django 5.0.6 on 2024-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('term', models.FloatField()),
                ('interest_paid', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('maturity', 'Maturity')], max_length=50)),
            ],
        ),
    ]
