# Generated by Django 5.0.6 on 2024-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_termdeposit_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termdeposit',
            name='interest_paid',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('at_maturity', 'At Maturity')], max_length=50),
        ),
    ]
